services:
  wild-tour-app:
    image: wild-tour:phase5
    container_name: wild-tour-app
    environment:
      DB_URL: jdbc:mysql://database-wild-tour.cfyo6wgou1au.ap-south-1.rds.amazonaws.com:3306/wildlife
      DB_USER: wildlife-docker
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - wild-tour-network
networks:
  wild-tour-network:
